FROM ros:crystal

# install ros packages for installed release
#RUN apt-get update
#RUN apt-get install -y ros-crystal-demo-nodes-cpp ros-crystal-demo-nodes-py ros-crystal-sros2
#RUN rm -rf /var/lib/apt/lists/*

# run ros package launch file
#CMD ["ros2", "launch", "demo_nodes_cpp", "talker_listener.launch.py"]
